/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.martinsmayhem.mymoney;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mike@asylum.martinsmayhem.com
 */
public class StartupDialog extends javax.swing.JDialog {
    private final AppConfig config;
    private final DefaultListModel<String> recentModel = new DefaultListModel<>();
    private Database database;


    /**
     * Creates new form StartupDialog
     */
    public StartupDialog(java.awt.Frame parent, boolean modal, AppConfig config) {
        super(parent, modal);
        this.config = config;
        initComponents();
        recentList.setModel(recentModel);
        loadRecent();
        getRootPane().setDefaultButton(openButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recentList = new javax.swing.JList<>();
        openButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open Database");

        jLabel1.setText("Recent Databases");

        recentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        recentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recentList);

        openButton.setText("Open");
        openButton.setPreferredSize(new java.awt.Dimension(90, 24));
        openButton.addActionListener(this::openButtonActionPerformed);

        newButton.setText("New");
        newButton.setPreferredSize(new java.awt.Dimension(90, 24));
        newButton.addActionListener(this::newButtonActionPerformed);

        browseButton.setText("Browse");
        browseButton.setPreferredSize(new java.awt.Dimension(90, 24));
        browseButton.addActionListener(this::browseButtonActionPerformed);

        removeButton.setText("Remove");
        removeButton.setPreferredSize(new java.awt.Dimension(90, 24));
        removeButton.addActionListener(this::removeButtonActionPerformed);

        exitButton.setText("Exit");
        exitButton.setPreferredSize(new java.awt.Dimension(90, 24));
        exitButton.addActionListener(this::exitButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        String sel = recentList.getSelectedValue();
        if (sel == null) {
            JOptionPane.showMessageDialog(this, "Select a database from the list first.");
            return;
        }
        openFile(Paths.get(sel));
    }//GEN-LAST:event_openButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        NewDatabaseDialog nd = new NewDatabaseDialog(null, true, config);
        nd.setLocationRelativeTo(this);
        nd.setVisible(true);
        if (nd.getDatabase() != null) {
            database = nd.getDatabase();
            dispose();
        }
    }//GEN-LAST:event_newButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        fc.setDialogTitle("Open a MyMoney database");
        fc.setFileFilter(new FileNameExtensionFilter(
                "MyMoney databases (*." + Database.EXTENSION + ")", Database.EXTENSION));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            openFile(fc.getSelectedFile().toPath());
        }        
    }//GEN-LAST:event_browseButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String sel = recentList.getSelectedValue();
        if (sel == null) return;
        try { config.removeRecent(sel); } catch (SQLException ignored) { }
        loadRecent();        
    }//GEN-LAST:event_removeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void recentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentListMouseClicked
        if (evt.getClickCount() == 2 && recentList.getSelectedValue() != null) {
            openFile(Paths.get(recentList.getSelectedValue()));
        }        
    }//GEN-LAST:event_recentListMouseClicked

    public Database getDatabase() {
        return database;
    }

    private void loadRecent() {
        recentModel.clear();
        try {
            for (String p : config.getRecentDatabases()) recentModel.addElement(p);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Could not read recent list: " + e.getMessage());
        }
        if (!recentModel.isEmpty()) recentList.setSelectedIndex(0);
    }

    private void openFile(Path file) {
        if (!Files.isRegularFile(file)) {
            int r = JOptionPane.showConfirmDialog(this,
                    "This file could not be found:\n" + file + "\n\nRemove it from the list?",
                    "File Not Found", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
                try { config.removeRecent(file.toString()); } catch (SQLException ignored) { }
                loadRecent();
            }
            return;
        }
        JPasswordField pf = new JPasswordField(20);
        int r = JOptionPane.showConfirmDialog(this, pf, "Password for " + file.getFileName(),
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (r != JOptionPane.OK_OPTION) return;
        char[] pw = pf.getPassword();
        try {
            database = Database.open(file, new String(pw));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Could not open the database. The password may be wrong,\n"
                    + "or the file may not be a MyMoney database.",
                    "Open Failed", JOptionPane.ERROR_MESSAGE);
            return;
        } finally {
            Arrays.fill(pw, '\0');
        }
        try { config.addRecent(file); } catch (SQLException ignored) { }
        dispose();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JList<String> recentList;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
