/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.martinsmayhem.mymoney;

import java.awt.Component;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mike@asylum.martinsmayhem.com
 */
public class StartupDialog extends javax.swing.JDialog {
    private final AppConfig config;
    private final DefaultListModel<String> recentModel = new DefaultListModel<>();
    private Database database;
    private String defaultPath; 

    /**
     * Creates new form StartupDialog
     */
        public StartupDialog(java.awt.Frame parent, boolean modal, AppConfig config) {
        super(parent, modal);
        this.config = config;
        initComponents();
        recentList.setModel(recentModel);
        recentList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value,
                    int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null && value.equals(defaultPath)) {
                    setText(value + "   (default)");
                }
                return this;
            }
        });
        loadRecent();
        getRootPane().setDefaultButton(openButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRecentDB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recentList = new javax.swing.JList<>();
        openButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        defaultButton = new javax.swing.JButton();
        clearDefaultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open Database");

        labelRecentDB.setText("Recent Databases");

        recentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        recentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recentList);

        openButton.setText("Open");
        openButton.setMaximumSize(new java.awt.Dimension(125, 24));
        openButton.setMinimumSize(new java.awt.Dimension(125, 24));
        openButton.setPreferredSize(new java.awt.Dimension(125, 24));
        openButton.addActionListener(this::openButtonActionPerformed);

        newButton.setText("New");
        newButton.setMaximumSize(new java.awt.Dimension(125, 24));
        newButton.setMinimumSize(new java.awt.Dimension(125, 24));
        newButton.setPreferredSize(new java.awt.Dimension(125, 24));
        newButton.addActionListener(this::newButtonActionPerformed);

        browseButton.setText("Browse");
        browseButton.setMaximumSize(new java.awt.Dimension(125, 24));
        browseButton.setMinimumSize(new java.awt.Dimension(125, 24));
        browseButton.setPreferredSize(new java.awt.Dimension(125, 24));
        browseButton.addActionListener(this::browseButtonActionPerformed);

        removeButton.setText("Remove");
        removeButton.setMaximumSize(new java.awt.Dimension(125, 24));
        removeButton.setMinimumSize(new java.awt.Dimension(125, 24));
        removeButton.setPreferredSize(new java.awt.Dimension(125, 24));
        removeButton.addActionListener(this::removeButtonActionPerformed);

        exitButton.setText("Exit");
        exitButton.setMaximumSize(new java.awt.Dimension(125, 24));
        exitButton.setMinimumSize(new java.awt.Dimension(125, 24));
        exitButton.setPreferredSize(new java.awt.Dimension(125, 24));
        exitButton.addActionListener(this::exitButtonActionPerformed);

        defaultButton.setText("Set as Default");
        defaultButton.setMaximumSize(new java.awt.Dimension(125, 24));
        defaultButton.setMinimumSize(new java.awt.Dimension(125, 24));
        defaultButton.setPreferredSize(new java.awt.Dimension(125, 24));
        defaultButton.addActionListener(this::defaultButtonActionPerformed);

        clearDefaultButton.setText("Clear Default");
        clearDefaultButton.setMaximumSize(new java.awt.Dimension(125, 24));
        clearDefaultButton.setMinimumSize(new java.awt.Dimension(125, 24));
        clearDefaultButton.setPreferredSize(new java.awt.Dimension(125, 24));
        clearDefaultButton.addActionListener(this::clearDefaultButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRecentDB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearDefaultButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defaultButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRecentDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearDefaultButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        String sel = recentList.getSelectedValue();
        if (sel == null) {
            JOptionPane.showMessageDialog(this, "Select a database from the list first.");
            return;
        }
        openFile(Paths.get(sel));
    }//GEN-LAST:event_openButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        NewDatabaseDialog nd = new NewDatabaseDialog(null, true, config);
        nd.setLocationRelativeTo(this);
        nd.setVisible(true);
        if (nd.getDatabase() != null) {
            database = nd.getDatabase();
            dispose();
        }
    }//GEN-LAST:event_newButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        fc.setDialogTitle("Open a MyMoney database");
        fc.setFileFilter(new FileNameExtensionFilter(
                "MyMoney databases (*." + Database.EXTENSION + ")", Database.EXTENSION));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            openFile(fc.getSelectedFile().toPath());
        }        
    }//GEN-LAST:event_browseButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String sel = recentList.getSelectedValue();
        if (sel == null) return;
        try { config.removeRecent(sel); } catch (SQLException ignored) { }
        loadRecent();        
    }//GEN-LAST:event_removeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void recentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentListMouseClicked
        if (evt.getClickCount() == 2 && recentList.getSelectedValue() != null) {
            openFile(Paths.get(recentList.getSelectedValue()));
        }        
    }//GEN-LAST:event_recentListMouseClicked

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        String sel = recentList.getSelectedValue();
        if (sel == null) {
            JOptionPane.showMessageDialog(this, "Select a database from the list first.");
            return;
        }
        try {
            config.setDefaultDatabase(Paths.get(sel));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Could not set default: " + e.getMessage());
        }
        loadRecent();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void clearDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDefaultButtonActionPerformed
        try {
            config.clearDefaultDatabase();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Could not clear default: " + e.getMessage());
        }
        loadRecent();
    }//GEN-LAST:event_clearDefaultButtonActionPerformed

    public Database getDatabase() {
        return database;
    }

    private void loadRecent() {
        String previous = recentList.getSelectedValue();
        recentModel.clear();
        try {
            defaultPath = config.getDefaultDatabase();
            for (String p : config.getRecentDatabases()) recentModel.addElement(p);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Could not read recent list: " + e.getMessage());
        }
        if (previous != null && recentModel.contains(previous)) {
            recentList.setSelectedValue(previous, true);
        } else if (defaultPath != null && recentModel.contains(defaultPath)) {
            recentList.setSelectedValue(defaultPath, true);
        } else if (!recentModel.isEmpty()) {
            recentList.setSelectedIndex(0);
        }
    }

    private void openFile(Path file) {
        if (!Files.isRegularFile(file)) {
            int r = JOptionPane.showConfirmDialog(this,
                    "This file could not be found:\n" + file + "\n\nRemove it from the list?",
                    "File Not Found", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
                try { config.removeRecent(file.toString()); } catch (SQLException ignored) { }
                loadRecent();
            }
            return;
        }
        Database opened = PasswordPrompt.open(this, file);
        if (opened == null) return;          // user cancelled
        database = opened;
        try { config.addRecent(file); } catch (SQLException ignored) { }
        dispose();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton clearDefaultButton;
    private javax.swing.JButton defaultButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRecentDB;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JList<String> recentList;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
